SquirrelTracking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sightings.urls')),
]

sightings/urls.py
from django.urls import path

from . import views

app_name = 'sightings-view'

urlpatterns = [
    path('', views.index, name='index'),
    path('sightings/', views.sightings, name='sightings'),
    path('sightings/add/', views.add, name='add'),
    path('sightings/stats/', views.stats, name='stats'),
    path('map/', views.map, name = 'map'),
    path('sightings/<str:unique_squirrel_id>/', views.detail, name='detail'),
]

sightings/models.py
from django.db import models


class Squirrel(models.Model):
    latitude = models.FloatField(null=False, blank=False)
    longitude = models.FloatField(null=False, blank=False)
    unique_squirrel_id = models.CharField(max_length=100, unique=True, null=False, blank=False)
    AM = 'AM'
    PM = 'PM'
    OTHER = ''
    shift_choice = [
        (AM, 'AM'),
        (PM, 'PM'),
        (OTHER, '')
    ]
    shift = models.CharField(
        max_length=15,
        choices=shift_choice,
        default=OTHER,
    )


    date = models.DateField(null=True, blank=True)
    age = models.CharField(max_length=5, blank=True)
    primary_fur_color = models.CharField(max_length=50, blank=True)
    location = models.CharField(max_length=50, blank=True)
    specific_location = models.CharField(max_length=50, blank=True)
    other_activities = models.CharField(max_length=100, blank=True)
    running = models.BooleanField()
    chasing = models.BooleanField()
    climbing = models.BooleanField()
    eating = models.BooleanField()
    foraging = models.BooleanField()
    kuks = models.BooleanField()
    quaas = models.BooleanField()
    moans = models.BooleanField()
    tail_flags = models.BooleanField()
    tail_twitches = models.BooleanField()
    approaches = models.BooleanField()
    indifferent = models.BooleanField()
    runs_from = models.BooleanField()

    def __str__(self):
        return self.unique_squirrel_id
# Create your models here.

sightings/forms.py
from django.forms import ModelForm

from .models import Squirrel


class AddRequestForm(ModelForm):
    class Meta:
        model = Squirrel
        # All other fields are handled in the background
        fields = '__all__'


class UpdateRequestForm(ModelForm):
    class Meta:
        model = Squirrel
        # All other fields are handled in the background
        fields = [
            'latitude',
            'longitude',
            'unique_squirrel_id',
            'shift',
            'date',
            'age',
        ]

sightings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Avg, Max, Min, Count
from .models import Squirrel
from .forms import AddRequestForm
from .forms import UpdateRequestForm


def index(request):
    squirrels = Squirrel.objects.all()
    context = {'squirrels': squirrels}
    return render(request, 'sightings/home.html', context)


def map(request):
    squirrels = Squirrel.objects.all()[:100]
    context = {'squirrels': squirrels}
    return render(request, 'sightings/map.html', context)


def sightings(request):
    squirrels = Squirrel.objects.all()
    context = {'squirrels': squirrels}
    return render(request, 'sightings/sightings.html', context)


def detail(request, unique_squirrel_id):
    squirrel = Squirrel.objects.get(unique_squirrel_id=unique_squirrel_id)
    if request.method == "POST":
        form = UpdateRequestForm(request.POST, instance=squirrel)
        if form.is_valid():
            form.save()
            return redirect('/sightings/')
    else:
        form = UpdateRequestForm(instance=squirrel)
    return render(request, 'sightings/detail.html', {'form': form, 'unique_squirrel_id': unique_squirrel_id})


def add(request):
    if request.method == "POST":
        form = AddRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/sightings/add')
    else:
        form = AddRequestForm()
    return render(request, 'sightings/add.html', {'form': form})


def stats(request):
    squirrels = Squirrel.objects.all()
    total = Squirrel.objects.count()
    avg_lat = squirrels.aggregate(Avg('latitude')).get('latitude__avg')
    avg_long = squirrels.aggregate(Avg('longitude')).get('longitude__avg')
    climbing = squirrels.filter(climbing=True).count()
    chasing = squirrels.filter(chasing=True).count()
    # age = list(squirrels.values_list('age').annotate(Count('age')))
    context = {
        'total': total,
        'avg_lat': avg_lat,
        'avg_long': avg_long,
        'climbing': climbing,
        'chasing': chasing,
        # 'age': age,
    }

    return render(request, 'sightings/stats.html', context)

sightings/templates/sightings/add.html
{% extends 'sightings/base.html' %}
{% load bootstrap %}

{% load static %}

{% block main %}
<head>
    <meta charset="UTF-8">
    <style>
        h1 {
            color: black;
            text-align: center;
        }
        .topnav {
            overflow: hidden;
            background-color: #333;

        }
        .topnav a {
            display: block;
            color: white;
            text-align: center;
            text-decoration: none;
            font-family: cursive;
            font-size: large;
        }


        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        .button{
            height: 50px;
            text-align: center;

        }

        .items{
            display:flex;
            align-content:space-around;
            align-items:center;
        }

        .form{
            display: flex;
            flex-flow: column;
            align-content:center;
            align-items:center;
            justify-content: space-around;
        }


    </style>
    <title>Squirrel Sightings at Central Park in 2018</title>
</head>

<h1 text-align:center>Create a New Sighting</h1>


<p>
{#    {{ form | boo }}#}
<form action="" method="post">{% csrf_token %}
    <table align="center">{{ form }}</table>
    <br>
    <div class="button">
        <input type="submit" class='button btn btn-outline-secondary' value="Submit" style="height:50px;width:100px">
    </div>
</form>

</p>
{% endblock %}
{% block extra_footer %}
{% endblock %}

sightings/templates/sightings/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Sightings</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <!--&lt;!&ndash; Bootstrap core CSS &ndash;&gt;-->
    <!--<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
        html,body {
            height: 100%;
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        header {
            margin-bottom: 10px;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/album/album.css" rel="stylesheet">
</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <a class="navbar-brand" href="/">Sightings</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>

         <li class="nav-item">
             <a href="/sightings/" class="nav-link">View Sightings <span class="sr-only">(current)</span></a>
{#        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>#}
      </li>

         <li class="nav-item">
             <a href="/sightings/add/" class="nav-link">New Sightings <span class="sr-only">(current)</span></a>
      </li>

         <li class="nav-item">
             <a href="/sightings/stats/"  class="nav-link" >View Statistics <span class="sr-only">(current)</span></a>
      </li>



    </ul>

      <ul class="form-inline my-2 my-lg-0 navbar-nav">

      <li class="nav-item">
        <a class="nav-link" href="/admin/login">Admin Login</a>
      </li>
    </ul>


  </div>
</nav>
{##}
{#    <div class="collapse bg-dark" id="navbarHeader">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-sm-8 col-md-7 py-4">#}
{#                    <h4 class="text-white">About</h4>#}
{#                    <p class="text-muted">Do you want to checkout squirrels in NYC Central Park?</p>#}
{#                </div>#}
{#                <div class="col-sm-4 offset-md-1 py-4">#}
{#                    <h4 class="text-white">Contact</h4>#}
{#                    <ul class="list-unstyled">#}
{#                        <li><a href="#" class="text-white">Follow on Twitter</a></li>#}
{#                        <li><a href="#" class="text-white">Like on Facebook</a></li>#}
{#                        <li><a href="mailto:me@example.com" class="text-white">Email me</a></li>#}
{#                        <li><a href="{% url 'admin:login' %}" class="text-white">Admin Login</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#    <div class="navbar navbar-dark bg-dark shadow-sm">#}
{#        <div class="container d-flex justify-content-between">#}
{#            <a href="/" class="navbar-brand d-flex align-items-center">#}
{#                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>#}
{#                <strong>Sightings</strong>#}
{#            </a>#}
{#            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">#}
{#                <span class="navbar-toggler-icon"></span>#}
{#            </button>#}
{#        </div>#}
{#    </div>#}
</header>

<main role="main">
    {% block main %}
    {% endblock %}
</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
{#            <a href="#">Back to top</a>#}
        </p>
        <p>&copy; 2021 Central Park Squirrels, Inc.</p>
    </div>
</footer>

{# Don't use the slim version of jQuery! It does not have the ajax librarires! #}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
{% block extra_footer %}
{% endblock %}
</body>
</html>

sightings/templates/sightings/detail.html
{% extends 'sightings/base.html' %}

{% load static %}


{% block main %}
<head>
    <meta charset="UTF-8">
    <style>
        h1 {
            color: black;
            text-align: center;
            font-family: verdana;
            {#font-size: 250%;#}
        }
        {#div {#}
        {#    font-size: 70%;#}
        {#    font-family: courier;#}
        {#    display: flex;#}
        {#    align-content:space-around;#}
        {#    align-items:center;#}
        {#    justify-content: space-around;#}
        {#}#}
        .topnav {
            overflow: hidden;
            background-color: #333;

        }
        .topnav a {
            display: block;
            color: white;
            text-align: center;
            text-decoration: none;
            font-family: cursive;
            font-size: large;
        }


        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        p{
            marign-top: 80px;

        }

        .button{
            marign-top: 80px;
            text-align: center;

        }

        .items{
            display:flex;
            align-content:space-around;
            align-items:center;
        }

        .form{
            display: flex;
            flex-flow: column;
            align-content:center;
            align-items:center;
            justify-content: space-around;
        }




    </style>
    <title>Central Park Squirrel Sightings in 2020</title>
</head>

<p>
<form action="" method="post">{% csrf_token %}
    <table align="center">{{ form }}</table>
    <br>
    <div class="button">
        <input type="submit" class='button btn btn-dark' value="Update" style="height:50px;width:100px">
    </div>
</form>

</p>
{% endblock %}
{% block extra_footer %}
{% endblock %}

sightings/templates/sightings/home.html
{% extends 'sightings/base.html' %}

{% load static %}

{% block title %}Stats of squirrels{% endblock %}

{% block main %}

    <style>
        .card-img-top {
            width: 100%;
            height: 15vw;
            object-fit: cover;
        }

    </style>
    <div class="container-fluid">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleControls" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleControls" data-slide-to="1"></li>
{#                    <li data-target="#carouselExampleControls" data-slide-to="2"></li>#}
                </ol>
{#                <div class="carousel-item active">#}
{#                    <img class="d-block w-100" src="{% static 'sightings/c1.jpg' %}" alt="First slide">#}
{#                </div>#}
                <div class="carousel-item active">
                    <img class="d-block w-100" src="{% static 'sightings/c2.jpg' %}" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'sightings/c3.jpg' %}" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{% static 'sightings/squirrel_01.jpeg' %}" alt="views">
                    <div class="card-body">
                        <h5 class="card-title">Sightings</h5>
                        <p class="card-text">Sightings list</p>
                        <a href="/sightings" class="btn btn-outline-secondary">VIEW</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{% static 'sightings/stats.png' %}" alt="stats">
                    <div class="card-body">
                        <h5 class="card-title">Stats</h5>
                        <p class="card-text">Stats of Squirrels</p>
                        <a href="/sightings/stats" class="btn btn-outline-secondary">VIEW</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{% static 'sightings/squirrel_02.jpeg' %}" alt="add">
                    <div class="card-body">
                        <h5 class="card-title">Add</h5>
                        <p class="card-text">Add a new sighting</p>
                        <a href="/sightings/add" class="btn btn-outline-secondary">ADD</a>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{% static 'sightings/location.jpeg' %}" alt="map">
                    <div class="card-body">
                        <h5 class="card-title">Location</h5>
                        <p class="card-text">Location of sightings</p>
                        <a href="/map" class="btn btn-outline-secondary">VIEW</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

sightings/templates/sightings/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in squirrels %}
          var point_lat_lon = [{{ sighting.longitude }}, {{ sighting.latitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

sightings/templates/sightings/sightings.html
{% extends 'sightings/base.html' %}

{% load static %}

{% block title %} - {{ squirrel.age }}{% endblock %}

{% block main %}
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row justify-content-center">
      {% for squirrel in squirrels %}
      <div class="col-md-7">
        <div class="card mb-7 shadow-sm">
          <div class="card-body">
            <div class="pet-name">
              <h5>{{ squirrel.unique_squirrel_id }}</h5>
            </div>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted"  data-toggle="tooltip" data-placement="top" title="Seen Date">{{ squirrel.date }}&nbsp;&nbsp;{{ squirrel.location }}&nbsp;&nbsp;{{ squirrel.primary_fur_color }}</small>
{#              <small class="text-muted"  data-toggle="tooltip" data-placement="top" title="Seen Date">{{ squirrel.location }}</small>#}
              <div class="btn-group">
                <a class="btn btn-outline-dark" href="{% url 'sightings-view:detail' squirrel.unique_squirrel_id %}">View</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

sightings/templates/sightings/stats.html
{% extends 'sightings/base.html' %}

{% load static %}

{% block title %}Stats of squirrels{% endblock %}

{% block main %}
<!--<h1>Stats of Squirrels</h1>-->
<!--<br>-->
<!--<ul>-->
  <!--<li>Total of observations: {{ total }}</li>-->
  <!--<br>-->
  <!--<li>Average longitude: {{ avg_long }}</li>-->
  <!--<br>-->
  <!--<li>Average latitude: {{ avg_lat }}</li>-->
  <!--<br>-->
  <!--<li>age: {{ age }}</li>-->
  <!--<br>-->
  <!--<li>climbing: {{ climbing }}</li>-->
  <!--<br>-->
  <!--<li>chasing: {{ chasing }}</li>-->
<!--</ul>-->
<div class="container-fluid">
  <h1>Stats of Squirrels</h1>
  <ul class="list-group">
    <li class="list-group-item">
      Total of observations:
      <span class="badge">{{ total }}</span>
    </li>
    <li class="list-group-item">
      Average longitude:
      <span class="badge">{{ avg_long }}</span>
    </li>
    <li class="list-group-item">
      Average latitude:
      <span class="badge">{{ avg_lat }}</span>
    </li>
{#    <li class="list-group-item">#}
{#      Age:#}
{#      <span class="badge">{{ age }}</span>#}
{#    </li>#}
    <li class="list-group-item">
      Climbing:
      <span class="badge">{{ climbing }}</span>
    </li>
    <li class="list-group-item">
      Chasing:
      <span class="badge">{{ chasing }}</span>
    </li>
  </ul>
</div>

{% endblock %}